# Generated by Django 4.2.7 on 2023-12-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('ticker_symbol', models.CharField(max_length=10)),
                ('number_of_shares', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_share', models.DecimalField(decimal_places=2, max_digits=15)),
                ('image_filename', models.CharField(max_length=100)),
                ('transaction_valuation', models.DecimalField(decimal_places=2, max_digits=15)),
                ('overall_holdings', models.DecimalField(decimal_places=2, max_digits=15)),
                ('average_cost_per_share', models.DecimalField(decimal_places=2, max_digits=15)),
                ('realized_gain_loss', models.DecimalField(decimal_places=2, max_digits=15)),
                ('portfolio_valuation', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
    ]
